// src/vue/LiquidGlass.vue
<template>
  <div 
    ref="glassElement" 
    class="liquid-glass-wrapper"
    :style="wrapperStyles"
  >
    <slot></slot>
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted, watch, computed } from 'vue';
import { LiquidGlass } from '../core/LiquidGlass.js';
import { hexToRgb } from '../core/utils.js';

export default {
  name: 'LiquidGlass',
  props: {
    shadowColor: {
      type: String,
      default: 'rgba(255, 255, 255, 0.7)'
    },
    shadowBlur: {
      type: Number,
      default: 7
    },
    shadowSpread: {
      type: Number,
      default: 0
    },
    shadowOffset: {
      type: Number,
      default: 0
    },
    tintColor: {
      type: String,
      default: '#ffffff'
    },
    tintOpacity: {
      type: Number,
      default: 0.04
    },
    frostBlur: {
      type: Number,
      default: 2
    },
    noiseFrequency: {
      type: Number,
      default: 0.008
    },
    distortionStrength: {
      type: Number,
      default: 77
    },
    borderRadius: {
      type: Number,
      default: 28
    },
    width: {
      type: String,
      default: '300px'
    },
    height: {
      type: String,
      default: '200px'
    }
  },
  setup(props) {
    const glassElement = ref(null);
    let glassInstance = null;
    
    const wrapperStyles = computed(() => ({
      width: props.width,
      height: props.height
    }));
    
    const options = computed(() => ({
      shadowColor: props.shadowColor,
      shadowBlur: props.shadowBlur,
      shadowSpread: props.shadowSpread,
      shadowOffset: props.shadowOffset,
      tintColor: props.tintColor.startsWith('#') ? hexToRgb(props.tintColor) : props.tintColor,
      tintOpacity: props.tintOpacity,
      frostBlur: props.frostBlur,
      noiseFrequency: props.noiseFrequency,
      distortionStrength: props.distortionStrength,
      borderRadius: props.borderRadius
    }));
    
    onMounted(() => {
      if (glassElement.value) {
        glassInstance = new LiquidGlass(glassElement.value, options.value);
      }
    });
    
    onUnmounted(() => {
      if (glassInstance) {
        glassInstance.destroy();
      }
    });
    
    // Watch for prop changes
    watch(options, (newOptions) => {
      if (glassInstance) {
        Object.entries(newOptions).forEach(([key, value]) => {
          glassInstance.updateOption(key, value);
        });
      }
    }, { deep: true });
    
    return {
      glassElement,
      wrapperStyles
    };
  }
};
</script>

<style scoped>
.liquid-glass-wrapper {
  position: relative;
}
</style>

// src/react/LiquidGlass.jsx
import React, { useRef, useEffect } from 'react';
import { LiquidGlass } from '../core/LiquidGlass.js';
import { hexToRgb } from '../core/utils.js';

export const LiquidGlassReact = ({
  children,
  shadowColor = 'rgba(255, 255, 255, 0.7)',
  shadowBlur = 7,
  shadowSpread = 0,
  shadowOffset = 0,
  tintColor = '#ffffff',
  tintOpacity = 0.04,
  frostBlur = 2,
  noiseFrequency = 0.008,
  distortionStrength = 77,
  borderRadius = 28,
  width = '300px',
  height = '200px',
  className = '',
  style = {},
  ...props
}) => {
  const elementRef = useRef(null);
  const glassRef = useRef(null);
  
  useEffect(() => {
    if (elementRef.current) {
      const options = {
        shadowColor,
        shadowBlur,
        shadowSpread,
        shadowOffset,
        tintColor: tintColor.startsWith('#') ? hexToRgb(tintColor) : tintColor,
        tintOpacity,
        frostBlur,
        noiseFrequency,
        distortionStrength,
        borderRadius
      };
      
      glassRef.current = new LiquidGlass(elementRef.current, options);
    }
    
    return () => {
      if (glassRef.current) {
        glassRef.current.destroy();
      }
    };
  }, []);
  
  // Update on prop changes
  useEffect(() => {
    if (glassRef.current) {
      const options = {
        shadowColor,
        shadowBlur,
        shadowSpread,
        shadowOffset,
        tintColor: tintColor.startsWith('#') ? hexToRgb(tintColor) : tintColor,
        tintOpacity,
        frostBlur,
        noiseFrequency,
        distortionStrength,
        borderRadius
      };
      
      Object.entries(options).forEach(([key, value]) => {
        glassRef.current.updateOption(key, value);
      });
    }
  }, [shadowColor, shadowBlur, shadowSpread, shadowOffset, tintColor, tintOpacity, frostBlur, noiseFrequency, distortionStrength, borderRadius]);
  
  return (
    <div 
      ref={elementRef}
      className={`liquid-glass-wrapper ${className}`}
      style={{ width, height, ...style }}
      {...props}
    >
      {children}
    </div>
  );
};
